### ISSUE TITLE
[Feature Request] Animation on Show & Close

### ISSUE THREAD

**Issue by paulreyns** [Blazored/Modal#166]
Would be nice to be able to fade the modal in and out, I guess this could either be a different method outside the Show/Close or additional option on the ModalOptions parameter?

I did consider that you could add an additional class on the Class property on the ModalOptions which might allow you to do some css magic but it would be nice to be an option in its own right.

**Comment by chrissainty** [comment]
Hi @paulreyns, this is definitely something we could look to add. My capacity is extremely limited at the moment, more than happy to take a PR if you want to have a go and I'll put this up as an _Up For Grabs_ as well.

**Comment by larsk2009** [comment]
If @paulreyns doesn't have time to do it, I would like to help. I just have one question regardless of who implements it:

Are we going to support just Fade in/Fade out like @paulreyns said, or do we want to allow any css animation? I think this would make a bit of a difference in terms of how difficult the implementation would be.

**Comment by chrissainty** [comment]
Great, thanks @larsk2009! I would suggest starting simple and just handling fade-in fade-out.

**Comment by paulreyns** [comment]
I did manage to get it to fade & slide slightly in locally using css animation, but couldn't get it to animate out. I'm happy for someone to give it a bash as I'm fairly busy also but might get some time eventually.

**Comment by larsk2009** [comment]
I'll have a look then. I have some ideas for fading out, I'll keep everyone posted.

**Comment by larsk2009** [comment]
I have made a **very preliminary ** version of animating In and out. Please have a look at it and see if it is any good. It feels a little hacky this implementation because fading out and removing after that is not the cleanest thing. Some JS could improve animating out potentially but I haven't really looked into that too much.

Also, the example mentions a global animation like we have with the position options and such, but I haven't added that just yet.

Anyway, if you have time have a look and see if you like it. Then I will finish this up or change whatever is necessary.

**Comment by larsk2009** [comment]
I have improved my preliminary version of animations, and have raised a PR for it. Please have a look at it and let me know what you all think!
