### ISSUE TITLE
[Bug] No Modal Dialog is opened

### ISSUE THREAD

**Issue by DanielHWe** [Blazored/Modal#172]
**Describe the bug**
In my project (BlazorWebAssembly)
 `var messageForm = Modal.Show<NewGame>();`
`var result = await messageForm.Result;`
Does not open a Model dialog, there is no error, so  I have no clue what is not working.

**To Reproduce**
See https://github.com/DanielHWe/BlazorDiceGame/blob/master/Pages/Game.razor
1. Klick "New game"
2. ShowModal() is executed

**Expected behavior**
A Modal Dialog is opened

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by larsk2009** [comment]
Hi,

First of all, thank you for actually providing a very good reproduction of your problem. This greatly helps us find any issue, so thanks for that!

The reason it is not working is because there is no `<BlazoredModal />` in your `MainLayout.razor`. See [step 3](https://github.com/Blazored/Modal#3-add-modal-component) of the readme. When I added this to the code you provided, the modal shows.
