### ISSUE TITLE
[Feature] Offer Modal Service as a cascading value rather than requiring injection

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Modal#173]
I've been wondering recently whether the modal service being injected is the right thing to do. Looking at the designs from the Blazor team, they favour using cascading values to provide global concerns. AuthenticationState being a good example of this. 

The proposal is to provide a `CascadingModalService` component which can be added at the app level rather than requiring the developer to inject a modal service. Ideally, this would also replace the need for adding the `BlazoredModal` component to the `MainLayout`. 

I'm interested in others thoughts on this. Do you have any scenarios where an injected service is a necessity over a cascading value? Love to get some feedback on this idea.

**Comment by larsk2009** [comment]
Just so I correctly understand your proposel: The user would add the `CascadingModalService` in the app.razor just like `CascadingAuthenticationState` for example? Then the ModalService could be retrieved in a page with `[CascadingParameter]` instead of `[Inject]`? 

If this is the case, I think I like it. Especially if it can also replace the `BlazoredModal` component in the `MainLayout` like you mentioned. I have seen a couple of people forgetting to add this. Right now it is not so obvious to them, but if we are using a cascading value and it is null because they forget to add the `CascadingModalService `, it is more clear where the problem is I think.

Personally I don't think I have a scenario where injected service is a necessity. Maybe there are scenarios where inject is necessary but I cannot think of any right now.

**Comment by chrissainty** [comment]
Yes @larsk2009 that’s it. It just seems like it would solve several reoccurring setup issues we keep seeing, as you’ve pointed out. Without much of a down side. Unless I’ve missed something 🙂

**Comment by MichelJansson** [comment]
> I've been wondering recently whether the modal service being injected is the right thing to do. Looking at the designs from the Blazor team, they favour using cascading values to provide global concerns. AuthenticationState being a good example of this.
> 

This is interesting, do you have any links or docs regarding this for further reading?
Thanks.

**Comment by chrissainty** [comment]
@mhagrelius There aren't any official docs about this, as I said in my comment I'm looking at the general design choices the Blazor team have made.

**Comment by MichelJansson** [comment]
@chrissainty Thanks for the lightning fast reply. Ok, interesting none the less.

For me personally, who started using asp.net core last year because Blazor came around, it feels more intuitive to inject external things, and I would not expect to access a external service thru a cascading parameter.
One more thing for the toolbox when designing services - thanks!
