### ISSUE TITLE
Should/could the modal Close cause a complete page re-render? (Feature Request)

### ISSUE THREAD

**Issue by tomRedox** [Blazored/Modal#20]
As far as I can tell, at the moment when the modal is closed (not cancelled) it doesn't trigger the StateHasChanged at the top level?

There are probably a lot of cases where the logic performed on the modal will update the rest of the page, so I think it could be useful if there was an option to tell the modal to trigger a re-render?

I've got round this by wiring up a ModalClosed method, but it would be nice not to have to do this on every component that uses the modal.

Would it be possible to add a Parameter that tells the Modal whether it should re-render its the `Modal`'s parent and all its children (by parent I mean the component the modal is set up on and all of it's children, i.e. typically MainLayout.razor)?

**Comment by chrissainty** [comment]
Apologies Tom, I seemed to have let this one slip through the net. I’ll have a look into it and get back to you.

**Comment by chrissainty** [comment]
Hi @tomRedox, apologies for taking so long on this one. The idea is that you should handle the OnClose and decide what you want to happen. From a performance point of view you may not want a top level `StateHasChanged` to be called automatically, you may want to chose when that happens if at all. Also the `OnClose` event returns the `ModalResult` object which will contain anything returned from the modal instance. At this point I would probably prefer to leave things as is unless this is causing major issues?

**Comment by tomRedox** [comment]
Hi @chrissainty, no problem, just flagging it up as a thought.
