### ISSUE TITLE
[Question] Any option / best practices including RenderTemplate?

### ISSUE THREAD

**Issue by NatanBagrov** [Blazored/Modal#237]
Hi,

I've come across this issue while trying to make Modal more modular. For instance, take the basic "Yes/No" confirmation modal (seen in the examples). You can add a `string Content` property and initialize it with the content we wish do display. However, say I wish to show something more complex (for instance a list), I can create a dedicated Modal for that matter, but I was wondering if I can re-use the Confirmation Modal, passing-in a `RenderTemplate` or something of that kind, to render it within the component.

What I was thinking about is creating a wrapper component, which accepts a `[Parameter] RenderTemplate`, use (render) it inside the `.razor` page, referencing it through `ElementReference`, and executing a `ShowModal()` method from that reference, which 'pipes' the `RenderTemplate` to the Confirmation modal (which now accepts `RenderTemplate`).
I feel like this "piping" stuff is a bit redundant, and could be avoided.

Do you see any better, straight-forward way to do so?

**Comment by larsk2009** [comment]
I don't personally see a very straightforward way to do this. The solution I would first try is the one you already mentioned. Did you try that one and does it work?

I think the problem is, you want to pass a `RenderFragment` to the Modal? Normally you do this as the child element of the element you want to pass it to, but this is obviously not possible with the way modals work. The other way would be with a paramter to which you manually pass a `RenderFragment`, but then creating the `RenderFragment` becomes the problem I think. You can create it using code, but this is probably not what you are looking for, so I think your solution is your best bet, if it works.

Maybe @chrissainty has a better solution for this?

**Comment by NatanBagrov** [comment]
Hi @larsk2009, thank you for your response.
I indeed was able to implement this wrapper thingy, however I still use the previous version of Modal (think 4.x) due to breaking changes and lack of time in my side.
I also  "integrated" it, such that it is more robust, returning the `ModalReference` from the wrapper to the "caller" component, so that it would be able to make logic afterwards (as is returned from `ModalService`).

It feels like if there was an option to use the `<BlazoredModal>` component within every page (rather than `MainLayout.cshtml`, or `App.razor` in the newer version). However it smells like another breaking change...

**Comment by chrissainty** [comment]
Hi @NatanBagrov why would having the `<BlazoredModal>` component on every page solve the issue? That component does very little, it simply provides a container to display any modal instances.

I might not have understood what you're attempting, but using the list and yes/no example from your opening comment, you would just capture a reference to Blazored Modal in the list component and then call Modal.Show with your yes/no confirmation?

**Comment by NatanBagrov** [comment]
Hi @chrissainty, I'm afraid you misunderstood what I wrote.
I would like to be able to render custom content within the Modal.
So, I don't want to show the yes/no from every list item, but rather show the yes/no modal with the list content within it.
Think about this option:
```c#
<YesNoBlazoredModal>
<ul><li>#1</li><li>#2</li>
Are you sure?
...
</YesNoBlazoredModal>
```

**Comment by chrissainty** [comment]
I still don't think I understand what you're trying to do @NatanBagrov.

You want to display a modal which is a component called `MyModal`, for example. So you'd call `Modal.Show<MyModal>(...)`. Inside `MyModal` you want to display custom content? So your `MyModal` might look like this:

```razor
<h1>My Modal</h1>

<p>@CustomContent</p>

@code {
    [Parameter] public RenderFragment CustomContent { get; set; }
}
```

Is that correct?

**Comment by NatanBagrov** [comment]
Indeed, @chrissainty .
And I'm wondering if there's a better way to pass this `CustomContent`...

**Comment by David-Moreira** [comment]
@chrissainty I think @NatanBagrov's doubt is how to pass markup into the modal without having to use the RenderTreeBuilder is that not it?
Chris, In your example, would you be able to pass markup into the parameter CustomContent without RenderTreeBuilder?

**Comment by chrissainty** [comment]
@David-Moreira you could pass the markup as a string and then render it inside the component using `MarkupString`. Other than that I don't think there are any other ways. I guess question now is what's wrong with RenderFragments? The are the Blazor way of passing pieces of arbitrary UI

**Comment by David-Moreira** [comment]
Thank you for your answer Chris!
I don't think there's nothing wrong with it. That's how it works. Just saying that's what seemed @NatanBagrov's idea/question to me. 
Write his tidy markup as he has always known and pass it into the render fragment. In some cases, having to pass a whole lot of markup as string into RenderFragment,  doesn't seem really neat. 

For example, I'm guessing there's places where there's the front end guy, that just wants to write the markup and not have to care about all of this details, hell I bet he doesn't want to be learning how to "manually write" a RenderFragment.

Anyway that just happens when you try to use them in some specific ways, like @NatanBagrov's use case.
People, myself including are still wrapping their head around how some stuff work on blazor.

**Comment by NatanBagrov** [comment]
Hi @David-Moreira, thanks for stepping into the conversation. You are correct about my question. I was thinking about how to make the Modal more modular, and wondering whether there is some "more-native" way to achieve that. I guess not.
I'll stick with the wrapper anyways :)
