### ISSUE TITLE
Please makes it draggable and resizable 

### ISSUE THREAD

**Issue by NaserParhizkar** [Blazored/Modal#243]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jkears** [comment]
I second this... I really love the Modal but would love it more so if could to be able to drag and resize..

**Comment by larsk2009** [comment]
@jkears Could you give an example usage for this? I can't think of a use-case of the top of my head, but I am sure you have one. 😉 That way it is easier for us to imagine exactly what you and @NaserParhizkar want.

**Comment by jkears** [comment]
Sure...

I am creating a tool that captures business domains and from which code-generates the backing domain microservices..

Within the Domain modeling tool I am able to invoke a business rules editor (as modal).  

The rules are based upon the same schema as captured in the underlying domain model.  

I would be nice to be able to move and or minimize that dialog so that I can see underlying schema. 

![image](https://user-images.githubusercontent.com/1290937/98994411-be1f9a00-24fd-11eb-8b4b-eac40530b38e.png)


As once the rules editor modal is up I can't see the underlying schema...


![image](https://user-images.githubusercontent.com/1290937/98994467-dbecff00-24fd-11eb-819a-b863be94fa23.png)

**Comment by larsk2009** [comment]
Very good use-case indeed, thanks for that! I will have a look a this tomorrow.

**Comment by jkears** [comment]
Thank you.

**Comment by neriks** [comment]
I use Blazored.Modal extensively in several projects and just like @jkears I think it would be nice if dialogs can be moved (or minimized) in order to see the underlying contents. In one of my recent projects I urgently needed funtionality to move dialogs so I came up the the following work-around. The work-around is based on the "How TO - Create a Draggable HTML Element" example from from w3schools.com

https://www.w3schools.com/howto/howto_js_draggable.asp


I changed the example code from w3schools.com to target Blazor Javascript interop and Blazored.Modal.

```
window.BlazorModalExtensions =
{
  Draggable: function () {
    var elements = document.getElementsByClassName("blazored-modal-draggable");
    if (elements) {
      for (var i = 0; i < elements.length; i++) {
        // Setup draggable for each 'blazored-modal-overlay' ...
        var element = elements[i];
        dragElement(element);
      }
    }

    function dragElement(elmnt) {
      var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;

      childElements = document.querySelectorAll('.blazored-modal-draggable .blazored-modal-header');
      if ((childElements) && (childElements.length > 0)) {
        var childElement = childElements[0];
        childElement.onmousedown = dragMouseDown;
      }

      function dragMouseDown(e) {
        e = e || window.event;
        e.preventDefault();

        // Get the mouse cursor position at startup ...
        pos3 = e.clientX;
        pos4 = e.clientY;
        document.onmouseup = closeDragElement;

        // Call a function whenever the cursor moves ...
        document.onmousemove = elementDrag;
      }

      function elementDrag(e) {
        e = e || window.event;
        e.preventDefault();

        // Calculate the new cursor position ...
        pos1 = pos3 - e.clientX;
        pos2 = pos4 - e.clientY;
        pos3 = e.clientX;
        pos4 = e.clientY;

        // Set the element's new position ...
        elmnt.style.top = (elmnt.offsetTop - pos2) + "px";
        elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";
      }

      function closeDragElement() {
        // stop moving when mouse button is released ...
        document.onmouseup = null;
        document.onmousemove = null;
      }
    }
  }
}

```

I also altered the 'blazored-modal-header' CSS class in order to change the cursor when moving the dialog.

```
.blazored-modal-header {
  padding: 0.2rem;
  cursor: move;
  z-index: 10;
}

```

Finally I implemented a modal-options CSS class called 'blazored-modal-draggable'. The class is used for enabling absolute positioning of the dialog. The class is also used by the Javascript interopt code to indentify what element to move.

```
.blazored-modal-draggable {
  position: absolute;
  display: flex;
  z-index: 102;
  flex-direction: column;
  background-color: #fff;
  border-radius: 4px;
  border: 2px solid rgba(0, 123, 255, 0.8);
  padding: 0.4rem;
  box-shadow: 0 2px 2px rgba(0,0,0,.25);
  width: 60rem;
}

```


The Javascript interop code needs to be called when the dialog exist. Hence, calling it from the OnAfterRenderAsync turned out sufficient for the work-around.

```
protected override async Task OnAfterRenderAsync(bool firstRender)
{
  if (firstRender)
  {
    await JsRuntime.InvokeVoidAsync("BlazorModalExtensions.Draggable");
  }
   await base.OnAfterRenderAsync(firstRender);
}

```


Calling the dialog from C# is done be including the 'blazored-modal-draggable' CSS class in the ModalOptions parameter.

`Modal.Show<DraggableDialog>("Welcome to Blazored Modal", new ModalOptions() { Class = "blazored-modal-draggable" });
`



The code does not work for nested dialogs and it has only been tested briefly for Blazored server-side. However, it has worked well enough to meet my requirements so far.

I attached a working sample ...
[BlazorServer.zip](https://github.com/Blazored/Modal/files/5736030/BlazorServer.zip)

**Comment by chrissainty** [comment]
Ok, this is a really difficult one. While making the modal draggable would be cool there are a number of issues that it could introduce.

- Nested modals and if it could even work with them
- Z-indexing issues - relates to nested modals again
- How would this fit in with custom modals where the developers is providing there own layout code?
- How would this work on mobile devices?
- More JavaScript code would be added - not necessarily bad but more to maintain

I think if we did decide to implement this it would need a lot of thought and testing.

**Comment by jkears** [comment]
@chrissainty thank-you for your continued review of this request.  Your first four points above appear to be related to design decisions, of which, some are likely not good candidates for draggable.  As such, draggable should be an opt-in feature, determined by the needs of the design. 
 
Since the original intent was to be able to reveal what lies beneath a modal, perhaps to simplify this ask, how about adding an opt-in capability to include a minimize/maximize option instead.  That approach may resolve the mobile concern you raised however if it were an opt-in model, than it's highly likely this capability would not be opted-in on a mobile device anyway.

**Comment by chrissainty** [comment]
I think in some ways a minimize/maximise options is harder. For example, where do we minify to? How should it look when minimized? If you have multiple modals how does that work?

The opt-in approach is definitely a must but how do you envision developers opting out on mobile? In the world of responsive web apps the only way to do this, in my mind, would be to check the screen size which would require hooking into the resize events of the browser. 

The kind of behaviour talked about in this issue sounds very much like behaviour from desktop applications and very much opposed to how the web community views modals. 

The more I think about this the more I don't think this is a feature we would look to add to the library as it seems to add significant complexity for what I think is a niche use-case. I've worked on and used a lot of web apps over the years and this just isn't behaviour I have see much, if at all.

**Comment by jkears** [comment]
@chrissainty , you are totally correct, this is not a common behaviour and is more of an extension-to rather than a feature-of.  

Perhaps the real ask is what are the framework extensions capabilities that would be necessary to be able to incorporate this type of behaviour and do these exist?  

It seems that @neriks was able to make this work for his needs and so I am cool with implementing a solution similar to what @neriks has provided (thank-you @neriks).  

Cheers

**Comment by chrissainty** [comment]
@jkears I would suggest starting with the solution @neriks provided and see how you get on. Essentially, all this library is doing is displaying or hiding a few divs everything about it's look is dictated by CSS and you can make very dramatic changes by manipulating it. 

I'm going to go ahead and close this issue as a won't fix but I'm more than happy to keep chatting here and providing any assistance I can going forward.
