### ISSUE TITLE
Why Javascript?

### ISSUE THREAD

**Issue by pha3z** [Blazored/Modal#262]
I see you originally wrote a javascript-free modal.

It looks like the current modal requires a javascript dependency, but I don't see an explanation why.  Can the purpose be added to the readme?

Since the Telerik javascript-free modal comes up on Google, it sounds more appealing at first.  I had to do a lot of reading to see that the javascript-free version is a predecessor to this Blazored / Modal library.  Some explanation would help.

**Comment by chrissainty** [comment]
Hi @pha3z, out of curiosity why does the fact that we use some JavaScript concern you? It's a concern of the library not for you to deal with as developer consuming it?

**Comment by pha3z** [comment]
Thanks for the answer!

It concerns me only because I like to know exactly what goes on under the hood when I take dependencies into my projects. I have a habit of writing things from scratch when I can do it to avoid more dependencies...or if the way something works internally isn't preferred.

I've been using Blazored.modal quite happily.  It's fantastic! Great work and Thank you!

**Comment by chrissainty** [comment]
No problem and thank you for providing some background on the question. What you've said makes totally sense and I appreciate your kind words regarding the library 🙂.

**Comment by David-Moreira** [comment]
@chrissainty you're probably already aware, but there's focus API support on .NET 5.
Not sure how easy it is or not to replace the focustrap functionality with it, but could be a good replacement for focustrap if it's your plan to eventually migrate and support .NET5.

**Comment by chrissainty** [comment]
Hi @David-Moreira, unfortunately a focus trap requires far more that just the ability to focus an element. 

A focus trap dynamically finds all elements inside of a given element, that are focusable. Then whenever a user tabs, it intercepts the event and makes that the only elements to receive focus are those it found in the previous step. 

To my knowledge, this isn't something we could do with Blazor without JS interop - that's why we're using the library we're using.

**Comment by chrissainty** [comment]
Closing this as the original question has been answered.
