### ISSUE TITLE
[Bug] Rework the custom layout sample as it's currently broken

### ISSUE THREAD

**Issue by chrissainty** [Blazored/Modal#266]
**Describe the bug**
It was pointed out in #265 that the custom layout sample wasn't working as expected - clicking on the background didn't cancel the modal. My attempt at a quick fix fixed the original issue but created another, clicking anywhere cancelled the modal.

After a scan of the Bootstrap code for the modal we might need to reimplement this sample. The HTML structure they use has a single root element which means when adding an `@onclick' event to it it will capture all clicks on the background AND modal (the bug I created with my quick fix).  

@larsk2009 let me know if you have any thoughts on this.

**Comment by larsk2009** [comment]
I'll have a look at it. Something I saw already is that we should also hook up the close button in the header of the bootstrap modal. That is also not working right now.

**Comment by larsk2009** [comment]
So I had a look at how bootstrap does it themselves, and they are not super clear about it. It seems like they put the .modal-backdrop element as the last child of the `<body>` element, instead of somewhere near the modal. Anyway, I found a way to get it to work. It is a bit hacky maybe, so have a look at what you think. I made a PR for it just because it is easier to look at. #267
