### ISSUE TITLE
Keeping CascadingBlazoredModal component Inside CascadingAuthenticationState component Is not working in App.razor page.

### ISSUE THREAD

**Issue by MRakesh** [Blazored/Modal#343]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Blazor WebAssembly
 - etc...

**Additional context**
Keeping CascadingBlazoredModal component Inside CascadingAuthenticationState component Is not working in App.razor page. Getting can not process request message on browser
Ex
CascadingAuthenticationState
CascadingBlazoredModal
Route....
CascadingBlazoredModal
CascadingAuthenticationState

**Comment by chrissainty** [comment]
Hi @MRakesh, this scenario definitely works, as this is exactly the configuration we use in our Blazor applications at my work. Without more detail there isn't anything we can do to help. But I'd suggest this is a local configuration issue in your application. 

I'm going to close this due to lack of information. If you can provide some detailed information in the future we can take another look.

**Comment by MRakesh** [comment]
Iam using with pre rendering enabled . Does this work?

**Comment by larsk2009** [comment]
Hi @MRakesh, I am not sure if pre-rendering has any effect on this, but the best way to get your issue fixed is providing more context and details, or ideally providing an example project showing your issue, which we can open on our own machine and have a look at.
