### ISSUE TITLE
Cannot click <select> dropdowns inside the modal [Bug]

### ISSUE THREAD

**Issue by Lorenium** [Blazored/Modal#386]
**Describe the bug**
I can't click the select items inside my modal. I can manually select them with the tab button and expand it with the return key, but clicking does not expand the dropdown.

**To Reproduce**

```
<!-- Modal -->

<form class="input-form">
    <div class="row my-2">
        <div class="col">
            <label class="fs-5" for="selectRev"> Revision: </label>
        </div>

        <div class="col">
            <select class="form-select" id="selectRev">
                @if (ButtonData != null)
                {
                    @foreach (var rev in ButtonData.RevList)
                    {
                        <option value="@rev">@rev</option>
                    }
                }
            </select>
        </div>
    </div>

    <div class="row my-2">
        <div class="col">
            <label class="fs-5" for="selectApp"> App: </label>
        </div>

        <div class="col">
            <select class="form-select" id="selectApp">
                <option>APP1</option>
                <option>APP2</option>
                <option>APP3</option>
            </select>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col text-center">
            <button @onclick="@(e => ButtonData.Clicked(1,0))" type="button" class="btn btn-dark w-50">SEND</button>
        </div>
    </div>
</form>



@code {
    [CascadingParameter] BlazoredModalInstance ModalInstance { get; set; }

    [Parameter]
    public ButtonData ButtonData { get; set; }
}
```

```
<!-- Button to trigger modal -->
<button @onclick="@(() => ShowInputModal(CurrentButtonData))" class="btn btn-dark sendMidButtons btn-lg">
    MID @CurrentButtonData.MidNum
</button>

@code {
    [CascadingParameter] public IModalService Modal { get; set; }

    [Parameter]
    public ButtonData CurrentButtonData { get; set; }

    public void ShowInputModal(ButtonData bData)
    {
        var parameters = new ModalParameters();
        parameters.Add("ButtonData", bData);

        Modal.Show<InputModal>($"MID {@CurrentButtonData.MidNum} Properties", parameters);
    }

```

**Expected behavior**
Dropdown item exposes all the <option> child elements and expands when clicked.

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor WebAssembly

**Comment by chrissainty** [comment]
Can produce a repro project showing the issue please, then we can try and work out what's happening. Just for reference, we use Blazored Modal at my work and have lots of modals with select lists so I think it's probably a local config issue somewhere.

**Comment by Caleb1995** [comment]
Using blazored modal with syncfusion and dropdowns work but the search functionality on the dropdowns don't work.

**Comment by gianx10** [comment]
Hi
This is a common problem, also with different vendor controls. I have open a discussion about this problem (DevExpress controls don't work #404)
I have try with DevExpress and Blazor.Radzen and I have your problem: clicking does not expand the dropdown or datapicker.
This is the response, of DevExpress technical support:

"_In v21.2, we changed rendering of our ComboBox (and other drop-down components) to place the DropDown part outside the ComboBox element (see [ComboBox, Date Edit, and Time Edit - The DropDown rendering has changed](https://supportcenter.devexpress.com/ticket/details/t1035320)). This change was necessary to fix CSS conflicts that occurred for DropDown content in certain usage scenarios.
It's the main cause of this behavior._"

In this scenario, drop-down controls inside Blazored.Modal, don't work. I hope is possible to fix the problem, otherwise the control is unusable.

**Comment by gianx10** [comment]
There is another problem with DevExpress. If in DevExpress DxPopup, I open a component with Blazored.Modal, when the user close this component, fist close the under componet and later the Blazored.Modal

**Comment by chrissainty** [comment]
I'm closing this issue as the original author has never re-engaged and this issue looks to be local config problem which I assume they resolved.

**Comment by LoupaLoupa** [comment]
I had this issue and I fixed it by turning the property draggable to false and it started working again. Not sure why this cause the issue, maybe this can be investigated?

Hope this answer can help someone in the future experiencing the issue.
