### ISSUE TITLE
[Feature Request] Better Custom Styling of Modal Header and Close Button

### ISSUE THREAD

**Issue by haakonfp** [Blazored/Modal#466]
For projects who do not use Bootstrap, it seems that the default styling for the header/title is not there. For example, I have a project using TailwindCSS, and have fully removed Bootstrap from the project. The default styling of the modal is reduced to the base text color and the base text font, particularly for the ``<h3>`` and for the Close button/span.

Here is an example of how it looks without styling and without Bootstrap (although with Inter and black text as default):

![image](https://user-images.githubusercontent.com/59263866/196824320-4c4bfb1b-79b8-4524-ac9b-0b97da38349b.png)

Luckily, Tailwind supports arbitrary values (e.g. ``[&>div>h3]``) for targeting child elements, so I added this to target the ``<h3>`` and the Close button's ``<span>`` to add a hover effect. Here is an example of how it looks with some ModalOptions and Tailwind.

![image](https://user-images.githubusercontent.com/59263866/196824540-ac417ec0-1a2d-41bb-b198-6967d44e88e7.png)

```
var options = new ModalOptions()
{
    DisableBackgroundCancel = true,
    Size = ModalSize.Medium,
    Position = ModalPosition.Middle,
    Class = "[&>div>h3]:flex [&>div>h3]:items-center [&>div>h3]:text-3xl [&>div>h3]:font-semibold [&>div>button>span:hover]:text-white-500"
};
```

Despite ``[&>div>button>span:hover]`` being somewhat charming, I'd rather not have to use these arbitrary selectors much. An issue is that you also have to check the modal layout to figure out the hierarchy of elements and how to target them.

It would be nice to have better support for non-Bootstrap projects, like Tailwind and others, by giving easier control over the different elements. It may also be beneficial for general purposes to have more control over the title and close button styling (rather than having to remove them).

One potential solution is to introduce ModalOptions for, e.g., ``CustomTitleClass`` or similar. Thoughts?

**Comment by chrissainty** [comment]
Hi @haakonfp. 

Right now, the modal has minimal styling, by design, as everyone has there own way of doing things. The only reason it looks better by default with Bootstrap is Bootstrap provides styles for everything out of the box.

As you've shown, you can use Tailwinds arbitary values to style things, you could also create classes and use the [`@apply` directive](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply). You could even use the [custom layout](https://blazored.github.io/Modal/styling/custom-layout) feature and provide your own modal where you have total control over the markup and styling. 

I don't see the need to add even more customisation at this point as none of the above are overly taxing or difficult to implement.
