### ISSUE TITLE
Online demo of Blazored.Modal using assets from build process

### ISSUE THREAD

**Issue by natsuo** [Blazored/Modal#50]
I found this nugget in the [Blazor WebAssembly](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/webassembly?view=aspnetcore-3.0#standalone-deployment): 
> Standalone deployment assets are published to the
`bin/Release/{TARGET FRAMEWORK}/publish/{ASSEMBLY NAME}/dist` folder.

I've seen some Blazor libraries host a demo of their library on GitHub Pages. Could the Azure Pipelines be set to copy the assets from the WebAssembly build over to a `gh-pages` branch? Would make it easier for people to see some of the features without having to clone the library.

Also need to add a `.no-jekyll` file to the folder for GitHub Pages to host the demo page.

**Comment by chrissainty** [comment]
I agree we need this. But instead of having individual sites for all the components in the Blazored suite, I’d like to create a central docs site. 

Now, how that works I’m not quite sure yet. It may be that the central docs site just loads each projects GitHub pages site. I’m going to create a Home repo for Blazored where this can be tracked.

**Comment by natsuo** [comment]
That sounds like a good idea. 😸

The "Blazored Demo" could have one .razor page for each of the components, with tabs explaining each of the features with the accompanying demo buttons and whatnot.

**Comment by chrissainty** [comment]
This is now being tracked by https://github.com/Blazored/Home/issues/1 on the new Home repo so I'm going to close this issue in favor of that one.
