### ISSUE TITLE
Cleaner Method Call

### ISSUE THREAD

**Issue by mhagrelius** [Blazored/Modal#51]
Is there a technical reason why the Show(string, Type) syntax can't instead accept a generic parameter with a ComponentBase constraint for T? It seems like a nicer experience to do something like `Modal.Show<EditMovie>("Title")`.

e.g.
`Show<T>(....) where T : ComponentBase { }`

 I'd be more than happy to do some work on it and submit a pull request if this is an acceptable idea.

**Comment by chrissainty** [comment]
Hi @mhagrelius, the simple answer is no, I probably had this on a refactor list a long time ago which has since been lost in the depth of my notebook! 😆 . I completely agree using a generic parameter makes the whole experience much better. 

I'd be happy to take the PR, I see you've raised it already are you happy with it as is?

**Comment by mhagrelius** [comment]
Yes, unless you'd like me to break it out into some more individual methods instead of one large one.
