### ISSUE TITLE
OnClose not firing 

### ISSUE THREAD

**Issue by Artem124Krsk** [Blazored/Modal#70]
Hi! 
I`m try your sample ServerSideblazor. Method ModalClosed not fire when i close modal but it fire when i calling method Show second time. I`m using VS 2019 preview 6.

**Comment by chewabledrapery** [comment]
Hi,

I thought this was an issue but after advice from @chrissainty it turned out that I needed to call this.statehanged in my modal close procedure. Hope this resolves it for you it did for me 👍

**Comment by Artem124Krsk** [comment]
Hi!
Thanks a lot for your advice, that has worked for me! But I dont understand why its works.

**Comment by chrissainty** [comment]
@Artem124Krsk Hi, so the reason you need to call `StateHasChanged` is because the `OnClose` event happens outside Blazor's view and therefor it doesn't know the UI needs to be updated. Hence you have to tell it manually by calling `StateHasChanged`.

As you're all sorted I'm going to go ahead and close this issue. Please re-open if you feel there is still an outstanding problem.
