### ISSUE TITLE
From Version 2.x to 3.0

### ISSUE THREAD

**Issue by joseazevedo** [Blazored/Modal#90]
Hello
In version 2.x

```
Public static void OpenPage(string pageName, dynamic rec,IModalService modalService, Action<string, dynamic> action, string group = "std")
        {
                string MyPageName = $"MyProject.Pages.{group}.Pages." + pageName;
                Type MYTYPE = Type.GetType(MyPageName);
                ModalParameters ModalParams = new ModalParameters();
                ModalParams.Add("RecRef", rec);
                ModalParams.Add("executeOnValidate", action);
                ModalParams.Add("isModal", true);
                modalService.Show(pageName, MYTYPE, ModalParams);
        }
```

And in 3.0 this dont work anymore because i need to to include Show<_MyProject.Pages.std.Pages.MYPAGE_> but i cant use the MYTYPE like this: modal.Show<MYTYPE>(...)

```
Public static void OpenPage(string pageName, dynamic rec,IModalService modalService, Action<string, dynamic> action, string group = "std")
        {
                string MyPageName = $"MyProject.Pages.{group}.Pages." + pageName;
                Type MYTYPE = Type.GetType(MyPageName);
                ModalParameters ModalParams = new ModalParameters();
                ModalParams.Add("RecRef", rec);
                ModalParams.Add("executeOnValidate", action);
                ModalParams.Add("isModal", true);
                modalService.Show<MYTYPE>(pageName, ModalParams);
        }
```

**Comment by larsk2009** [comment]
You are right that you cannot do what you did in v2.x anymore in v3.x unless I am missing something. The v3.x function is using generics. The compiler needs to be able to infer the type at compile-time, which is not possible when using a variable for the type.

I can see this was changed by @chrissainty in [this](https://github.com/Blazored/Modal/commit/97bca4a268685205978d41b6356b4de2ffaed3e9#diff-58826149fdc94bd12ab901d71c514acaL66) commit. I think Show<T>() was chosen above the old Show() function because with the generic function you can easily constrain the type so only components can be passed to Show<T> and not all types. But Chris can probably explain this better than me.

Finally, I haven't tested this but I think you might be able to do what you want using reflection. See [this](https://stackoverflow.com/questions/232535/how-do-i-use-reflection-to-call-a-generic-method) link for a starting point. Like I said, I haven't tested that at all so it might not work in this specific case.

**Comment by chrissainty** [comment]
@joseazevedo I've added some new overloads to `Show` which allow the old type usage. It will be in the next release.

**Comment by joseazevedo** [comment]
Thanks a lot Chris.

Chris Sainty <notifications@github.com> escreveu no dia domingo, 19/01/2020
à(s) 10:18:

**Comment by kiwiingenuity** [comment]
Chris,
Really appreciate the new show overloads!
Can you also add these overloads to IModalService please?

**Comment by chrissainty** [comment]
@kiwiingenuity I've just pushed an update to NuGet. Let me know if you have any problems.

**Comment by joseazevedo** [comment]
Works like a charme. Ty Chris.

Chris Sainty <notifications@github.com> escreveu no dia segunda, 10/02/2020
à(s) 14:53:
