### ISSUE TITLE
ModalService.Close ?

### ISSUE THREAD

**Issue by aherrick** [Blazored/Modal#91]
HI Chris,

What is the purpose of passing Ok result when closing? Most often I don't have to pass anything back to the parent, so I'd think just calling "Close()" should work.

` ModalService.Close(ModalResult.Ok("Blah blah blah :) "));`

**Comment by chrissainty** [comment]
Hi, the short answer is it's probably a bit of extra work you shouldn't really have to do if you don't want to return something. The reason it's there is because no one has ever asked if it shouldn't :)

I think we could look at adding an additional overload to the `Close` method which would return a default OK result. You could then use a discard in your calling code to ignore that returned result object. What do you think?
